"""add seed to map

Revision ID: 554e25a7ab29
Revises: 13a352073651
Create Date: 2026-01-04 06:28:02.596896

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "554e25a7ab29"
down_revision: str | Sequence[str] | None = "13a352073651"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("maps", sa.Column("seed", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("maps", "seed")
    # ### end Alembic commands ###
