"""add_is_pregenerated_to_map

Revision ID: 5d2ff5620f7a
Revises: a154439a8865
Create Date: 2026-01-04 09:23:18.152968

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d2ff5620f7a"
down_revision: str | Sequence[str] | None = "a154439a8865"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("maps", sa.Column("is_pregenerated", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("maps", "is_pregenerated")
    # ### end Alembic commands ###
