"""add island_density to map

Revision ID: a154439a8865
Revises: 554e25a7ab29
Create Date: 2026-01-04 06:35:21.004724

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a154439a8865"
down_revision: str | Sequence[str] | None = "554e25a7ab29"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("maps", sa.Column("island_density", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("maps", "island_density")
    # ### end Alembic commands ###
